apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: roasted-mosquito-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: roasted-mosquito-python 
  name: roasted-mosquito-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: roasted-mosquito-python 
